apiVersion: v1
kind: Namespace
metadata:
  name: goalquest
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: goalquest-infra
  labels:
    istio-injection: enabled
